config { 
  type: "table" ,
  schema: "purchase"
  
}
with ben as 
(
  select Segment, Country, Product,Gross_Sales,Profit,
concat('group', ntile(4) over (partition by Segment order by Country))
as group_number
from sql-practice-391810.purchase.Finance1
)
  select Country, Product,Segment, Gross_Sales, Profit,
last_value(Profit) 
over (partition by Segment order by Product)
as most_popular
from ben




 