config {
    type: "table",
    schema: "purchase",
    
}

WITH
  ben AS (
  SELECT
    Segment,
    Country,
    Product,
    Gross_Sales,
    Profit,
    CONCAT('group', NTILE(4) OVER (PARTITION BY Segment ORDER BY Country)) AS group_number
  FROM
    sql-practice-391810.purchase.Finance1 )
SELECT
  country,
  Product,
  Segment,
  Gross_Sales,
  Profit,
  group_number,
  LAST_VALUE(Profit) OVER (PARTITION BY Segment ORDER BY Profit) AS most_popular
FROM
  ben
